version: '3'
services:
  app:
    environment:
      - VK_API_VERSION=5.199
    networks:
      - nginx-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  redis:
    image: "redis:7.2"
    ports:
      - "6379:6379"
  networks:
    nginx-network:
      external: true